---
sidebar: sidebar 
permalink: use/uninstall_acc.html 
keywords: astra, astra control center, uninstall, remove 
summary: Descreve como remover o Centro de Controle Astra e o Operador do Centro de Controle Astra. 
---
= Desinstale o Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Talvez seja necessário remover componentes do Astra Control Center se você estiver atualizando de uma versão de avaliação para uma versão completa do produto. Para remover o Centro de Controle Astra e o Operador do Centro de Controle Astra, execute os comandos descritos neste procedimento em sequência.

.O que você vai precisar
* Use a IU do Astra Control Center para desgerenciar tudo link:../use/unmanage.html#stop-managing-compute["clusters"].


.Passos
. Excluir Astra Control Center. O seguinte comando de exemplo é baseado em uma instalação padrão. Modifique o comando se você fez configurações personalizadas.
+
[listing]
----
kubectl delete -f astra_control_center_min.yaml -n netapp-acc
----
+
Resultado:

+
[listing]
----
astracontrolcenter.astra.netapp.io "astra" deleted
----
. Use o seguinte comando para excluir o `netapp-acc` namespace:
+
[listing]
----
kubectl delete ns netapp-acc
----
+
Resultado:

+
[listing]
----
namespace "netapp-acc" deleted
----
. Use o seguinte comando para excluir componentes do sistema do operador Astra Control Center:
+
[listing]
----
kubectl delete -f astra_control_center_operator_deploy.yaml
----
+
Resultado:

+
[listing]
----
namespace "netapp-acc-operator" deleted
customresourcedefinition.apiextensions.k8s.io "astracontrolcenters.astra.netapp.io" deleted
role.rbac.authorization.k8s.io "acc-operator-leader-election-role" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-manager-role" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-metrics-reader" deleted
clusterrole.rbac.authorization.k8s.io "acc-operator-proxy-role" deleted
rolebinding.rbac.authorization.k8s.io "acc-operator-leader-election-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "acc-operator-manager-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "acc-operator-proxy-rolebinding" deleted
configmap "acc-operator-manager-config" deleted
service "acc-operator-controller-manager-metrics-service" deleted
deployment.apps "acc-operator-controller-manager" deleted
----




== Encontre mais informações

* link:../release-notes/known-issues.html["Problemas conhecidos para desinstalar"]

