---
sidebar: sidebar 
permalink: use/view-clusters.html 
keywords: view cluster, cluster storage, cluster overview 
summary: Depois de adicionar clusters ao Astra Control Center, é possível exibir detalhes sobre o cluster, como localização, nós de trabalho, volumes persistentes e classes de storage. 
---
= Ver a integridade e os detalhes dos clusters
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Depois de adicionar clusters a serem gerenciados pelo Astra Control Center, é possível exibir detalhes sobre o cluster, como localização, nós de trabalho, volumes persistentes e classes de storage.

.Passos
. Na IU do Astra Control Center, selecione *clusters*.
. Na página *clusters*, selecione o cluster cujos detalhes deseja exibir.
. Veja as informações nas guias *Visão geral*, *armazenamento* e *atividade* para encontrar as informações que você está procurando.
+
** *Visão geral*: Detalhes sobre os nós de trabalho, incluindo seu estado.
** *Storage*: Os volumes persistentes associados à computação, incluindo a classe de armazenamento e o estado.
** *Atividade*: Mostra as atividades relacionadas ao cluster.





NOTE: Você também pode exibir informações de cluster a partir do Astra Control Center *Dashboard*. Na guia *clusters* em *Resumo de recursos*, você pode selecionar os clusters gerenciados, que o levam à página *clusters*. Depois de acessar a página *clusters*, siga as etapas descritas acima.
