---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking, environment, operational, operational environment, hosting, host, cluster, clusters 
summary: Comece a usar o Astra Control Center verificando o suporte para clusters, aplicações e navegador da Web do Kubernetes. 
---
= Requisitos do Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Comece verificando a prontidão do seu ambiente operacional, clusters de aplicativos, aplicativos, licenças e navegador da Web.



== Requisitos do ambiente operacional

O Astra Control Center requer um dos seguintes tipos de ambientes operacionais:

* Red Hat OpenShift Container Platform 4,6.8, 4,7 ou 4,8
* Fazendeiro 2,5
* Kubernetes 1,19 a 1,21 (incluindo 1,21.x)


Certifique-se de que o ambiente operacional escolhido para hospedar o Astra Control Center atenda aos requisitos básicos de recursos descritos na documentação oficial do ambiente. O Astra Control Center requer os seguintes recursos, além dos requisitos de recursos do ambiente:

|===
| Componente | Requisito 


| Capacidade de storage do ONTAP no back-end | Pelo menos 300GB disponível 


| Nós de trabalho | Pelo menos 3 nós de trabalho no total, com 4 núcleos de CPU e 12GB GB de RAM cada 


| Balanceador de carga | Tipo de serviço "LoadBalancer" disponível para envio de tráfego de entrada para serviços no cluster do ambiente operacional 


| Resolução FQDN | Um método para apontar o FQDN do Astra Control Center para o endereço IP balanceado de carga 


| Astra Trident  a| 
* Astra Trident 21,04 ou mais recente instalado e configurado se o NetApp ONTAP versão 9,5 ou mais recente for usado como back-end de storage
* Astra Trident 21.10.1 ou mais recente instalado e configurado se a prévia do armazenamento de dados Astra for usada como um back-end de storage


|===

NOTE: Esses requisitos presumem que o Astra Control Center é a única aplicação em execução no ambiente operacional. Se o ambiente estiver executando aplicativos adicionais, ajuste esses requisitos mínimos de acordo.

* *Registro de imagem*: Você deve ter um Registro de imagem Docker privado existente para o qual você pode enviar imagens de compilação do Astra Control Center. Você precisa fornecer o URL do Registro de imagens onde você vai carregar as imagens.
* *Configuração Astra Trident / ONTAP*: O Astra Control Center requer que uma classe de storage seja criada e definida como a classe de storage padrão. O Astra Control Center é compatível com os seguintes drivers ONTAP fornecidos pelo Astra Trident:
+
** ONTAP-nas
** ONTAP-san
** ONTAP-são-economia




[NOTE]
====
Durante a clonagem de aplicativos em ambientes OpenShift, o Astra Control Center precisa permitir que o OpenShift monte volumes e altere a propriedade dos arquivos. Por causa disso, você precisa configurar uma política de exportação de volume ONTAP para permitir essas operações. Você pode fazer isso com os seguintes comandos:

. `export-policy rule modify -vserver <storage virtual machine name> -policyname <policy name> -ruleindex 1 -superuser sys`
. `export-policy rule modify -vserver <storage virtual machine name> -policyname <policy name> -ruleindex 1 -anon 65534`


====

NOTE: Se você pretende adicionar um segundo ambiente operacional do OpenShift como um recurso de computação gerenciado, precisa garantir que o recurso Snapshot de volume do Astra Trident esteja ativado. Para habilitar e testar snapshots de volume com o Astra Trident, https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html["Consulte as instruções oficiais do Astra Trident"^].



== Requisitos do cluster de aplicativos

O Astra Control Center tem os seguintes requisitos para clusters que você planeja gerenciar a partir do Astra Control Center. Esses requisitos também se aplicam se o cluster que você planeja gerenciar for o cluster do ambiente operacional que hospeda o Astra Control Center.

* A versão mais recente do Kubernetes https://kubernetes-csi.github.io/docs/snapshot-controller.html["componente do controlador snapshot"^] é instalada
* Um Astra Trident https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html["volumesnapshotclass objeto"^] foi definido por um administrador
* Existe uma classe de storage padrão do Kubernetes no cluster
* Pelo menos uma classe de storage está configurada para usar o Astra Trident



NOTE: Seu cluster de aplicativos deve ter um `kubeconfig.yaml` arquivo que define apenas um elemento _context_. Visite a documentação do Kubernetes para https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["informações sobre a criação de arquivos kubeconfig"^].


NOTE: Ao gerenciar clusters de aplicativos em um ambiente Rancher, modifique o contexto padrão do cluster de aplicativos no `kubeconfig` arquivo fornecido pelo Rancher para usar um contexto de plano de controle em vez do contexto do servidor da API Rancher. Isso reduz a carga no servidor de API Rancher e melhora o desempenho.



== Requisitos de gerenciamento de aplicativos

O Astra Control tem os seguintes requisitos de gerenciamento de aplicações:

* *Licenciamento*: Para gerenciar aplicações usando o Astra Control Center, você precisa de uma licença do Astra Control Center.
* *Namespaces*: O Astra Control requer que um aplicativo não abranja mais do que um namespace único, mas um namespace pode conter mais de um aplicativo.
* *StorageClass*: Se você instalar um aplicativo com um StorageClass explicitamente definido e precisar clonar o aplicativo, o cluster de destino para a operação clone deverá ter o StorageClass especificado originalmente. Clonar um aplicativo com um StorageClass explicitamente definido para um cluster que não tenha o mesmo StorageClass falhará.
* *Recursos do Kubernetes*: As aplicações que usam recursos do Kubernetes não coletados pelo Astra Control podem não ter recursos completos de gerenciamento de dados do aplicativo. O Astra Control coleta os seguintes recursos do Kubernetes:
+
** ClusterRole
** ClusterRoleBinding
** ConfigMap
** CustomResourceDefinition
** CustomResource
** DaemonSet
** Implantação
** DeploymentConfig
** Entrada
** MutatingWebhook
** PersistentVolumeClaim
** Pod
** ReplicaSet
** RoleBinding
** Função
** Rota
** Segredo
** Serviço
** Contagem de serviço
** StatefulSet
** ValidatingWebhook






=== Métodos de instalação de aplicativos suportados

O Astra Control é compatível com os seguintes métodos de instalação de aplicações:

* *Arquivo manifesto*: O Astra Control suporta aplicativos instalados a partir de um arquivo manifesto usando kubectl. Por exemplo:
+
[listing]
----
kubectl apply -f myapp.yaml
----
* *Helm 3*: Se você usar o Helm para instalar aplicativos, o Astra Control requer o Helm versão 3. O gerenciamento e clonagem de aplicativos instalados com o Helm 3 (ou atualizados do Helm 2 para o Helm 3) é totalmente compatível. O gerenciamento de aplicativos instalados com o Helm 2 não é suportado.
* *Aplicativos implantados pelo operador*: O Astra Control suporta aplicativos instalados com operadores com escopo de namespace. A seguir estão alguns aplicativos que foram validados para este modelo de instalação:
+
** https://github.com/k8ssandra/cass-operator/tree/v1.7.1["Apache K8ssandra"^]
** https://github.com/jenkinsci/kubernetes-operator["Jenkins CI"^]
** https://github.com/percona/percona-xtradb-cluster-operator["Cluster Percona XtraDB"^]





NOTE: Um operador e o aplicativo que ele instala devem usar o mesmo namespace; talvez seja necessário modificar o arquivo .yaml de implantação para que o operador garanta que esse seja o caso.



== Acesso à internet

Você deve determinar se você tem acesso externo à Internet. Se não o fizer, algumas funcionalidades poderão ser limitadas, como receber dados de monitorização e métricas do NetApp Cloud Insights, ou enviar pacotes de suporte para o https://mysupport.netapp.com/site/["Site de suporte da NetApp"^].



== Licença

O Astra Control Center requer uma licença do Astra Control Center para todos os recursos. Obtenha uma licença de avaliação ou uma licença completa da NetApp. Sem uma licença, você não poderá:

* Definir aplicações personalizadas
* Criar snapshots ou clones de aplicações existentes
* Configurar políticas de proteção de dados


Se você quiser experimentar o Astra Control Center, você pode link:setup_overview.html#add-a-full-or-evaluation-license["use uma licença de avaliação de 90 dias"].



== Tipo de serviço "LoadBalancer" para clusters do Kubernetes no local

O Astra Control Center usa um serviço do tipo "LoadBalancer" (svc/traefik no namespace Astra Control Center) e exige que seja atribuído um endereço IP externo acessível. Se os balanceadores de carga forem permitidos no seu ambiente e você ainda não tiver um configurado, você poderá usar https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_LB_MetalLB.html#installing-the-metallb-load-balancer["MetalLB"^] para atribuir automaticamente um endereço IP externo ao serviço. Na configuração do servidor DNS interno, você deve apontar o nome DNS escolhido para o Astra Control Center para o endereço IP com balanceamento de carga.



== Requisitos de rede

O ambiente operacional que hospeda o Astra Control Center se comunica usando as seguintes portas TCP. Você deve garantir que essas portas sejam permitidas por meio de firewalls e configurar firewalls para permitir qualquer tráfego de saída HTTPS proveniente da rede Astra. Algumas portas exigem conectividade entre o ambiente que hospeda o Astra Control Center e cada cluster gerenciado (observado quando aplicável).

|===
| Fonte | Destino | Porta | Protocolo | Finalidade 


| PC do cliente | Astra Control Center | 443 | HTTPS | Acesso de IU / API - garanta que essa porta esteja aberta de ambas as maneiras entre o cluster que hospeda o Astra Control Center e cada cluster gerenciado 


| Consumidor de métricas | Nó de trabalho do Astra Control Center | 9090 | HTTPS | Comunicação de dados de métricas - garanta que cada cluster gerenciado possa acessar essa porta no cluster que hospeda o Astra Control Center (comunicação bidirecional necessária) 


| Astra Control Center | Serviço Cloud Insights hospedado (https://cloudinsights.netapp.com[]) | 443 | HTTPS | Comunicação Cloud Insights 


| Astra Control Center | Fornecedor de bucket de armazenamento Amazon S3 (https://my-bucket.s3.us-west-2.amazonaws.com/[]) | 443 | HTTPS | Comunicação de armazenamento Amazon S3 


| Astra Control Center | Consultor (https://activeiq.solidfire.com[]digital ) | 443 | HTTPS | Comunicação do Digital Advisor 
|===


== Navegadores da Web suportados

O Astra Control Center suporta versões recentes do Firefox, Safari e Chrome com uma resolução mínima de 1280 x 720.



== O que vem a seguir

Veja a link:quick-start.html["início rápido"] visão geral.
